#include <bits/stdc++.h>
#include<iostream>

using namespace std;
int main(){
    int A[100];
    int B[100];
    for(int a=0;a<3;a++){
        cin>>A[a];
         }  
    for(int a=0;a<3;a++)
       {
        cin>>B[a];
       }
     int Ca[2]={0,0};
    for(int b=0;b<3;b++){
        if(A[b]>B[b])
        {   
            Ca[0]=Ca[0]+1;
        }
        if(A[b]<B[b])
        {
            Ca[1]=Ca[1]+1;
            
        }
        if(A[b]=B[b])
        {
            Ca[0]=Ca[0]+0;
            Ca[1]=Ca[1]+0;
        }
    } 
    for(int c=0;c<2;c++){
        cout<<Ca[c]<<" ";
    }
    return 0;
    
}
